### PR TITLE
feat: [input/textarea] add ignoreCompositionEvent

### PR DESCRIPTION
**Pull request by Tsong-LC**
[support ignoreCompositionEvent](https://gitee.com/dcloud/unidocs-zh/commit/4cf55edcc2e9588be443000434c11e5feb72e224)

### CODE REVIEW

**Comment by Tsong-LC** [comment]
Can someone review this PR? @BeiQiaoT

**Comment by BeiQiaoT** [comment]
LGTM.

**Comment by BeiQiaoT** [comment]
有兴趣的话也可以给 [文档](https://github.com/umicro/uView2.0-doc)加上属性哦

**Comment by Tsong-LC** [comment]
> 有兴趣的话也可以给 [文档](https://github.com/umicro/uView2.0-doc)加上属性哦

I will update.

**Pull request merged**
